version: 2
updates:
  # Infrastructure
  ## GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
    groups:
      gh-actions:
        #applies-to: version-updates
        patterns: ["*"]
    commit-message:
      prefix: "deps(ci)"
